<%@ Page Language="C#" AutoEventWireup="true" CodeFile="cl1.aspx.cs" Inherits="cl1" %>

<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">

<html xmlns="http://www.w3.org/1999/xhtml">
<head runat="server">
    <title></title>
     <style type="text/css">
        
         


body, html {
  height: 100%;
   margin: 0;
   background-color:#34495E;
  padding: 0;
  font-family: sans-serif;
}
.box input[type = "text"],.box input[type = "password"]{
  border:0;
  background: none;
  display: block;
  margin: 5px auto;
  text-align: center;
  border: 2px solid #3498db;
  padding: 14px 10px;
  width: 300px;
  outline: none;
  color:#FFFFCC;
  border-radius: 24px;
  transition: 0.25s;
}

.box input[type = "text"]:focus,.box input[type = "password"]:focus{
  width: 280px;
  border-color: #2ecc71;
}
.box input[type = "submit"]{
  border:0;
  background: #99ffcc;
  display: block;
  margin: 20px auto;
  text-align: center;
  border: 2px solid #2ecc71;
  padding: 14px 40px;
  outline: none;
  color: black;
  border-radius: 24px;
  transition: 0.25s;
  cursor: pointer;
}
.box input[type = "submit"]:hover{
  background: #2ecc71;
}
div.box{
  width: 800px;
  padding: 40px;
  position: absolute;
  top: 85%;
  left: 50%;
  transform: translate(-50%,-50%);
  text-align: center;
}
.box h1{
  color: white;
  text-transform: uppercase;
  font-weight: 500;
}
 div.user
    {
  position: absolute;
  top: 20px;
  left: 30px;
  width: 250px;
  height: 20px;
  font-size :25px;
  background-color:orange;
        }
div.header
    {
        height:100px;
       background-color:orange;
       padding-bottom:0px;
    }
.cc,.cc1
{
      border:0;
  background:#8EE4AF ;
  display: block;
  margin: 20px auto;
  text-align: center;
  border: 2px solid #2ecc71;
  padding: 14px 40px;
  outline: none;
  color: black;
  border-radius: 24px;
  transition: 0.25s;
  cursor: pointer;

}
.cc:hover
{
     background-color:#A30D3c;
    border:2px solid #A30D3c;
}
.cc1:hover
{
    background-color: #A30D3c;
}
.tablink:hover {
  background-color: #777;
}

div.logout
{
  position: absolute;
  top: 0px;
  right:10px;
  width: 150px;
  height: 50px;
  font-size :30px;
  background-color:Orange;
}
      
     
         .style1
         {
             color: #FFFFFF;
         }
      
     
         </style>
</head>
<body>
  
     <form class="box" id="form2" runat="server">
<div class ="header">
<div class="user">
   
    <asp:Label ID="Label" runat="server" Text="Welcome....."></asp:Label>
    </div> 
    <div class="logout">
    <asp:Button ID="logout" Width="120px" class="cc" runat="server" Text="Logout" 
            onclick="logout_Click1" UseSubmitBehavior="False" ValidationGroup="c"/>
    </div>
    </div>
    <table align="center">
    <tr><td colspan="5"> <asp:TextBox ID="sid" placeholder="Student ID" runat="server" ValidationGroup="t"></asp:TextBox></td>
        <td><asp:Button ID="Button1" runat="server" onclick="Button1_Click" Text="Submit" 
                ValidationGroup="t" /></td>
    <td>
        <asp:RequiredFieldValidator ID="RequiredFieldValidator1" runat="server" 
            ErrorMessage="Student ID Required" ControlToValidate="sid" ForeColor="White"></asp:RequiredFieldValidator> </td>
    </tr>
      <tr><td>&nbsp;</td>
          <td>&nbsp;</td>
          <td>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</td>
          <td><asp:Label ID="Label1" runat="server"
              style="text-align: center"></asp:Label></td>
          <td>&nbsp;</td>
          <td>&nbsp;</td>
          <td>&nbsp;</td>
        </tr>

 </table>
 <hr />
  <asp:ScriptManager ID ="ScriptMannager1" runat ="server"></asp:ScriptManager>
  <asp:Timer ID="Timer1" runat="server" Interval="10" OnTick="Timer1_Tick"></asp:Timer>
  <asp:UpdatePanel ID="UpdatePanel1" runat="server"><ContentTemplate>
  <asp:GridView ID="GridView1" runat="server" AutoGenerateColumns="False" 
         DataKeyNames="sid" align="center" Width="550px" DataSourceID="SqlDataSource1" 
         AutoGenerateDeleteButton="True" ForeColor="White" style="text-align: center">
         <Columns>
             <asp:BoundField DataField="name" HeaderText="name" SortExpression="name" />
             <asp:BoundField DataField="sid" HeaderText="sid" ReadOnly="True" 
                 SortExpression="sid" />
         </Columns>
     </asp:GridView>
     </ContentTemplate><Triggers><asp:AsyncPostBackTrigger ControlID="Timer1" EventName="Tick" /></Triggers></asp:UpdatePanel>
  
     <asp:SqlDataSource ID="SqlDataSource1" runat="server" 
         ConnectionString="<%$ ConnectionStrings:RegistrationConnectionString %>" 
         SelectCommand="select manager.name,cl.sid from manager,cl where manager.sid = cl.sid"  DeleteCommand="DELETE from [cl] where[sid]=@sid">
         <DeleteParameters>
             <asp:Parameter Name="sid" />
         </DeleteParameters>
     </asp:SqlDataSource>
    </form>
</body>
</html>
